name:                blah

dependencies:
- base >= 4.7 && < 5
- wrong-package >= 0.2

library:
  source-dirs: src

executables:
  blah-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - blah
