name:                blah

dependencies:
- base >= 4.7 && < 5
- say >= 100.2.0.1

library:
  source-dirs: src

executables:
  blah-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - blah
